-- Query 1 
SELECT * FROM EMPLOYEES WHERE ADDRESS LIKE '%Elgin%';

-- Query 2 
SELECT * FROM EMPLOYEES WHERE YEAR(B_DATE) LIKE '197%';

-- alternately
-- SELECT * FROM EMPLOYEES WHERE YEAR(B_DATE) >= 1970 AND YEAR(B_DATE) < 1980;

-- Query 3
SELECT *  FROM EMPLOYEES WHERE SALARY BETWEEN 60000 AND 70000;

-- Query 4
SELECT * FROM EMPLOYEES ORDER BY EMP_ID;

-- Query 4B
SELECT * FROM EMPLOYEES ORDER BY DEP_ID DESC, L_NAME DESC;

-- Query 5
SELECT COUNT(*), DEP_ID  FROM EMPLOYEES GROUP BY DEP_ID;

-- Query 5B
SELECT COUNT(*), AVG(SALARY), DEP_ID  FROM EMPLOYEES GROUP BY DEP_ID;

-- Query 5C
SELECT COUNT(*) AS NUM_EMPLOYEES,  AVG(SALARY) AS AVG_SALARY, DEP_ID 
FROM EMPLOYEES GROUP BY DEP_ID;

-- Query 5D
SELECT COUNT(*) AS NUM_EMPLOYEES,  AVG(SALARY) AS AVG_SALARY, DEP_ID 
FROM EMPLOYEES GROUP BY DEP_ID ORDER BY AVG_SALARY;

-- Query 5E
SELECT COUNT(*) AS NUM_EMPLOYEES,  AVG(SALARY) AS AVG_SALARY, DEP_ID 
FROM EMPLOYEES GROUP BY DEP_ID HAVING COUNT(*)<4
ORDER BY AVG_SALARY;

-- BONUS: Query 6

